---
title: "ltaw_text_explore"
author: "Bernice Cheung"
date: "2023-08-21"
date: "2023-08-21"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(psych)
library(ggplot2)
library(stringr)
library(knitr)
library(lme4)
library(lmerTest)
library(nFactors)
library(corrplot)
library(janitor)
library(kableExtra)
library(GPArotation)
library(here)
library(RColorBrewer)
library(broom)
library(sjPlot)
library(text)
```

# prep{.tab}

## load dataset{.tabset}
```{r}
survey_df <- read.csv(here("outputs", "ltaw_df_std_110823.csv")) %>%
  filter(flag_rec_include == T)
moment_df <- read.csv(here("outputs", "ltaw_moments_std_170823.csv")) %>%
  filter(flag_invalid_moment == FALSE) %>%
  filter(flag_dup_moment == FALSE)
```

## merge data
```{r}
moment_merge <- moment_df %>%
  left_join(select(survey_df, userid, swls_tot), by = "userid")

moment_merge_100 <- moment_merge[1:100,]

moment_student_wellness <- moment_df %>%
  left_join(select(survey_df, userid, swls_tot, student_status_prolific), by = "userid") %>%
  filter(student_status_prolific == "Yes") %>%
  filter(prompt_category == "Well-being")

moment_student_goal <- moment_df %>%
  left_join(select(survey_df, userid, swls_tot, student_status_prolific), by = "userid") %>%
  filter(student_status_prolific == "Yes") %>%
  filter(prompt_category == "Goals")

moment_goal <- moment_df %>%
  left_join(select(survey_df, userid, swls_tot, student_status_prolific), by = "userid") %>%
  filter(prompt_category == "Goals")

moment_wellness <- moment_df %>%
  left_join(select(survey_df, userid, swls_tot, student_status_prolific), by = "userid") %>%
  filter(prompt_category == "Well-being")

#write.csv(moment_merge, here("outputs", "moment_merge.csv"), row.names = F)
#write.csv(moment_merge[1:1000,], here("outputs", "moment_merge_1000.csv"), row.names = F)
#write.csv(moment_student_wellness, here("outputs", "moment_student_wellness.csv"), row.names = F)
#write.csv(moment_student_goal, here("outputs", "moment_student_goal.csv"), row.names = F)
#write.csv(moment_wellness, here("outputs", "moment_wellness.csv"), row.names = F)
#write.csv(moment_goal, here("outputs", "moment_goal.csv"), row.names = F)
```

## set environment 
```{r}
library(text)

# Install text required python packages in a conda environment (with defaults).
textrpp_install()

# Initialize the installed conda environment.
# save_profile = TRUE saves the settings so that you don't have to run textrpp_initialize() after restarting R. 
textrpp_initialize(save_profile = TRUE)
```

# generate embedding
```{r}
# Transform the text data to BERT word embeddings
word_embeddings <- textEmbed(
  texts = moment_merge$transcript[1:100],
  model = "bert-base-uncased",
  layers = -2,
  aggregation_from_tokens_to_texts = "mean",
  aggregation_from_tokens_to_word_types = "mean",
  keep_token_embeddings = FALSE)
```

```{r}
saveRDS(word_embeddings, here("outputs","word_embedding_100.rds"))
```

```{r}
# Examine the relationship between harmonytext word embeddings and the harmony in life rating scale
model_swls_100 <- textTrain(word_embeddings$texts$texts, 
                              moment_merge_100$swls_tot)
```

```{r}
model_htext_hils$results
```

```{r}
# Pre-process data
moment_merge_test <- moment_merge[200:299,]

projection_results <- textProjection(
  words = moment_merge_100$swls_tot,
  word_embeddings = word_embeddings$texts,
  word_types_embeddings = word_embeddings$word_types,
  x = moment_merge_100$swls_tot,
  #y = moment_merge_100$prompt_category
)
projection_results$word_data
```

```{r}
# Supervised Dimension Projection Plot
plot_projection_2D <- textProjectionPlot(
  word_data = projection_results,
 min_freq_words_plot = 1,
 plot_n_word_extreme = 10,
 plot_n_word_frequency = 5,
 plot_n_words_middle = 5,
 #y_axes = TRUE,
 p_alpha = 0.05,
 p_adjust_method = "fdr",
  title_top = "Harmony Words Responses (Supervised Dimension Projection)",
  x_axes_label = "Low vs. High Harmony in Life Scale Score",
  #y_axes_label = "Low vs.High Age",
  bivariate_color_codes = c("#E07f6a", "#60A1F7", "#85DB8E",
                            "#FF0000", "#EAEAEA", "#5dc688",
                            "#E07f6a", "#60A1F7", "#85DB8E"
))
# View plot
plot_projection_2D$final_plot
```





# test

```{r}
moment_test <- moment_student_wellness[1:200,]
```

```{r}
library(text)

# View example data including both text and numerical variables
Language_based_assessment_data_8

# Transform the text data to BERT word embeddings
w <- textEmbed(
  texts = moment_test[4],
  model = "bert-base-uncased",
  layers = -2,
  aggregation_from_tokens_to_texts = "mean",
  aggregation_from_tokens_to_word_types = "mean",
  keep_token_embeddings = FALSE)

# See how word embeddings are structured
w

# Save the word embeddings to avoid having to import the text every time. (i.e., remove the ##)
saveRDS(w, "wordembeddeding_student_wellness.rds")

# Get the word embeddings again (i.e., remove the ##)
## word_embeddings <- readRDS("_YOURPATH_/word_embeddings.rds")
```
```{r}
# Examine the relationship between harmonytext word embeddings and the harmony in life rating scale
test <- textTrain(w$texts$transcript, 
                              moment_test$swls_tot)

# Examine the correlation between predicted and observed Harmony in life scale scores
test$results

saveRDS(test, "models_student_wellbeing_200.rds")
```
```{r}
# Pre-process data
projection_results <- textProjection(
  words = moment_test$transcript,
  word_embeddings = w$texts,
  word_types_embeddings = w$word_types,
  x = moment_test$swls_tot,
  #y = Language_based_assessment_data_8$age
)
projection_results$word_data
```

```{r}
options(ggrepel.max.overlaps = 1000)

# Supervised Dimension Projection Plot
plot_projection_2D <- textProjectionPlot(
  word_data = projection_results,
 min_freq_words_plot = 1,
 plot_n_word_extreme = 10,
 plot_n_word_frequency = 5,
 plot_n_words_middle = 5,
 #y_axes = TRUE,
 p_alpha = 0.05,
 p_adjust_method = "fdr",
  title_top = "Well-being moment (Supervised Dimension Projection)",
  x_axes_label = "Overall life satisfaction",
  #y_axes_label = "Low vs.High Age",
  bivariate_color_codes = c("#E07f6a", "#60A1F7", "#85DB8E",
                            "#FF0000", "#EAEAEA", "#5dc688",
                            "#E07f6a", "#60A1F7", "#85DB8E"
))
# View plot
plot_projection_2D$final_plot
```

```{r}
feedback_data <- survey_df %>%
  select(userid, outro) %>%
  rename("transcript" = "outro") %>%
  filter(transcript!="")

#write.csv(feedback_data,here("outputs", "feedback_data.csv"), row.names = F)
```

